fix: lint check

diff --git a/bin/check b/bin/check
--- a/bin/check
+++ b/bin/check
@@ -18,31 +18,29 @@
 #
 
 md5r() {
-  if [ -e md5sum ] ; then
-    echo $RANDOM | md5sum
-  elif [ -e md5 ] ; then
-    md5 -q -s $RANDOM
-  fi
+    if [ -e md5sum ]; then
+        echo $RANDOM | md5sum
+    elif [ -e md5 ]; then
+        md5 -q -s $RANDOM
+    fi
 }
 
 # ヘルプ表示
 # ----------
-if [[ $# < 2 ]]; then
-  echo
-  echo "使い方: $0 <github user> <id_rsa>"
-  echo
-  echo "- <github user> : あなたの GitHub アカウント名"
-  echo "- <id_rsa>      : GitHub で公開している公開鍵のペアとなる秘密鍵のパス"
-  echo
-  exit 1
+if [[ $# -lt 2 ]]; then
+    echo
+    echo "使い方: ${0} <github user> <id_rsa>"
+    echo
+    echo "- <github user> : あなたの GitHub アカウント名"
+    echo "- <id_rsa>      : GitHub で公開している公開鍵のペアとなる秘密鍵のパス"
+    echo
+    exit 1
 fi
-
 
 # コマンド引数取得
 # ----------------
 USERNAME=$1
 SECRETKEY=$2
-
 
 # trap の設定
 # -----------
@@ -50,87 +48,76 @@ SECRETKEY=$2
 # - 参考URL ： https://qiita.com/m-yamashita/items/889c116b92dc0bf4ea7d
 trap "rm -rf ./sample.*" 0
 
-
 # サンプル・テキストの作成
 # ------------------------
-SAMPLETEXT=`md5r`
+SAMPLETEXT=$(md5r)
 SAMPLETEXT='hoge'
 
 # サンプル・ファイル名設定
 # ------------------------
-FILENAME=`md5r`
+FILENAME=$(md5r)
 PATHFILE="./sample.${FILENAME}.txt"
-
 
 # サンプル・ファイルの作成
 # ------------------------
 echo -n "サンプル・ファイルを作成しています ... "
-echo $SAMPLETEXT > $PATHFILE
 
-if [[ $? != 0 ]]; then
-  echo "NG：サンプル・ファイルの作成に失敗しました。"
-  echo "サンプル・ファイル名： ${PATHFILE}"
-  exit 1
+if ! echo $SAMPLETEXT >"$PATHFILE"; then
+    echo "NG：サンプル・ファイルの作成に失敗しました。"
+    echo "サンプル・ファイル名： ${PATHFILE}"
+    exit 1
 fi
 echo "OK"
-
 
 # サンプル・ファイルの暗号化
 # --------------------------
 echo -n "サンプル・ファイルを暗号化しています ... "
-RESULT=`enc ${USERNAME} ${PATHFILE} 2>&1`
 
-if [[ $? != 0 ]]; then
-  echo "NG：サンプル・ファイルの暗号化に失敗しました。"
-  echo "スクリプトの実行権限、ディレクトリの書き込み権限などを確認ください。"
-  exit 1
+if ! RESULT=$(enc "$USERNAME" "$PATHFILE" 2>&1); then
+    echo "NG：サンプル・ファイルの暗号化に失敗しました。"
+    echo "スクリプトの実行権限、ディレクトリの書き込み権限などを確認ください。"
+    exit 1
 fi
 echo "OK"
-
 
 # サンプル・ファイルの復号
 # ------------------------
 echo -n "暗号ファイルを復号しています ... "
-RESULT=`dec ${SECRETKEY} ${PATHFILE}.enc ${PATHFILE}.dec 2>&1`
 
-if [[ $? != 0 ]]; then
-  echo "NG：暗号ファイルの復号中にエラーが発生しました。"
-  echo "スクリプトの実行権限、ディレクトリの書き込み権限などを確認ください。"
-  exit 1
+if ! RESULT=$(dec "$SECRETKEY" "${PATHFILE}.enc" "${PATHFILE}.dec" 2>&1); then
+    echo "NG：暗号ファイルの復号中にエラーが発生しました。"
+    echo "スクリプトの実行権限、ディレクトリの書き込み権限などを確認ください。"
+    echo "Error: ${RESULT}"
+    exit 1
 fi
 echo "OK"
-
 
 # サンプル・ファイルの比較
 # ------------------------
 echo -n "オリジナルと復号ファイルを比較しています ... "
 
-diff $PATHFILE $PATHFILE.dec
-
-if [[ $? != 0 ]]; then
-  echo "NG：オリジナルと復号されたファイルが異なります。"
-  echo "オリジナル："
-  cat $PATHFILE; echo
-  echo "復号："
-  cat $PATHFILE.dec; echo
-  exit 1
+if ! diff "$PATHFILE" "${PATHFILE}.dec"; then
+    echo "NG：オリジナルと復号されたファイルが異なります。"
+    echo "オリジナル："
+    cat "${PATHFILE}"
+    echo
+    echo "復号："
+    cat "${PATHFILE}.dec"
+    echo
+    exit 1
 fi
 echo "OK"
-
 
 # サンプル・ファイルの削除
 # ----------------------
 echo -n "サンプル・ファイルの削除中 ... "
-rm $PATHFILE
-rm $PATHFILE.enc
 
-if [[ $? != 0 ]]; then
-  echo "NG：一時ファイルの削除に失敗しました。 手動で削除してください。"
-  echo "ファイル名： ${PATHFILE}"
-  exit 1
+if ! ( rm "$PATHFILE" && rm "${PATHFILE}.enc" ); then
+    echo "NG：一時ファイルの削除に失敗しました。 手動で削除してください。"
+    echo "ファイル名： ${PATHFILE}"
+    exit 1
 fi
 echo "OK"
-
 
 # 終了表示
 # --------
@@ -138,4 +125,3 @@ echo
 echo "暗号化・復号のテストを終了しました。"
 echo "✅ 問題なさそうです。"
 echo
-
