fix: openssl のエラーメッセージを出力するように修正

diff --git a/bin/check b/bin/check
--- a/bin/check
+++ b/bin/check
@@ -53,8 +53,11 @@ if [ ! -r "$SECRETKEY" ]; then
     echo >&2 "秘密鍵ファイル ${SECRETKEY} が見つかりません。"
     exit 1
 fi
-if ! openssl rsa -in "${SECRETKEY}" -text >/dev/null 2>/dev/null; then
+if ! RESULT="$(openssl rsa -in "${SECRETKEY}" -text 2>&1 >/dev/null)"; then
     echo >&2 "秘密鍵ファイル ${SECRETKEY} がサポートしていないフォーマットです。"
+    echo >&2
+    echo >&2 "Error(openssl)"
+    echo >&2 "$RESULT"
     exit 1
 fi
 
diff --git a/bin/dearchive b/bin/dearchive
--- a/bin/dearchive
+++ b/bin/dearchive
@@ -74,8 +74,11 @@ if [ -n "$PRIVATEKEYFILE" ]; then
         echo >&2 "秘密鍵ファイル ${PRIVATEKEYFILE} が見つかりません。"
         exit 1
     fi
-    if ! openssl rsa -in "${PRIVATEKEYFILE}" -text >/dev/null 2>/dev/null; then
+    if ! RESULT="$(openssl rsa -in "${PRIVATEKEYFILE}" -text 2>&1 >/dev/null)"; then
         echo >&2 "秘密鍵ファイル ${PRIVATEKEYFILE} がサポートしていないフォーマットです。"
+        echo >&2
+        echo >&2 "Error(openssl)"
+        echo >&2 "$RESULT"
         exit 1
     fi
 fi
diff --git a/bin/sign b/bin/sign
--- a/bin/sign
+++ b/bin/sign
@@ -73,8 +73,11 @@ if [ ! -r "$PRIVATEKEY" ]; then
     echo >&2 "秘密鍵ファイル ${PRIVATEKEY} が見つかりません。"
     exit 1
 fi
-if ! openssl rsa -in "${PRIVATEKEY}" -text >/dev/null 2>/dev/null; then
+if ! RESULT="$(openssl rsa -in "${PRIVATEKEY}" -text 2>&1 >/dev/null)"; then
     echo >&2 "秘密鍵ファイル ${PRIVATEKEY} がサポートしていないフォーマットです。"
+    echo >&2
+    echo >&2 "Error(openssl)"
+    echo >&2 "$RESULT"
     exit 1
 fi
 
